### ISSUE TITLE
I get a FileNotFoundException 

### ISSUE THREAD

**Issue by Frogy76** [sharplab/epub-translator#194]
Here is the complete process

```
java -jar .\build\epub-translator-runner.jar --src "C# Succinctly - Joe Mayo.epub" --dst "test2.epub"
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2024-05-02 19:52:08,150 INFO  [io.quarkus] (main) epub-translator 0.7.0-SNAPSHOT on JVM (powered by Quarkus 3.10.0) started in 1.265s.
2024-05-02 19:52:08,151 INFO  [io.quarkus] (main) Profile prod activated.
2024-05-02 19:52:08,151 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, config-yaml, hibernate-orm, hibernate-orm-panache-kotlin, jdbc-h2, kotlin, narayana-jta, picocli, rest-client, rest-client-jackson, smallrye-context-propagation, vertx]
2024-05-02 19:52:08,652 INFO  [net.sha.epu.cor.ser.EPubTranslatorServiceImpl] (main) OEBPS/nav.xhtml is translated.
2024-05-02 19:52:10,130 INFO  [net.sha.epu.cor.ser.EPubTranslatorServiceImpl] (main) OEBPS/Text/C_Sharp_Succinctly.html is translated.
2024-05-02 19:52:10,139 INFO  [net.sha.epu.cor.ser.EPubTranslatorServiceImpl] (main) OEBPS/Text/copyright.html is translated.
2024-05-02 19:52:10,140 INFO  [net.sha.epu.cor.ser.EPubTranslatorServiceImpl] (main) OEBPS/Text/cover_EPUB.html is translated.
2024-05-02 19:52:10,144 INFO  [net.sha.epu.cor.ser.EPubTranslatorServiceImpl] (main) OEBPS/Text/toc.html is translated.
java.io.FileNotFoundException: test2.epub (Das System kann die angegebene Datei nicht finden)
        at java.base/java.io.FileOutputStream.open0(Native Method)
        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:184)
        at net.sharplab.epubtranslator.core.driver.epub.EPubWriter.write(EPubWriter.kt:11)
        at net.sharplab.epubtranslator.app.service.EPubTranslatorAppServiceImpl.translateEPubFile(EPubTranslatorAppServiceImpl.kt:13)
        at net.sharplab.epubtranslator.app.cli.EPubTranslatorCli.run(EPubTranslatorCli.kt:29)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at io.quarkus.picocli.runtime.PicocliRunner$EventExecutionStrategy.execute(PicocliRunner.java:26)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at io.quarkus.picocli.runtime.PicocliRunner.run(PicocliRunner.java:40)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:132)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
2024-05-02 19:52:10,171 INFO  [io.quarkus] (main) epub-translator stopped in 0.024s
```

If I try to create an empty textfile it couldn't write to it

```
java -jar .\build\epub-translator-runner.jar --src "C# Succinctly - Joe Mayo.epub" --dst "test.epub"
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2024-05-02 19:55:37,678 INFO  [io.quarkus] (main) epub-translator 0.7.0-SNAPSHOT on JVM (powered by Quarkus 3.10.0) started in 1.304s.
2024-05-02 19:55:37,679 INFO  [io.quarkus] (main) Profile prod activated.
2024-05-02 19:55:37,679 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, config-yaml, hibernate-orm, hibernate-orm-panache-kotlin, jdbc-h2, kotlin, narayana-jta, picocli, rest-client, rest-client-jackson, smallrye-context-propagation, vertx]
2024-05-02 19:55:38,192 INFO  [net.sha.epu.cor.ser.EPubTranslatorServiceImpl] (main) OEBPS/nav.xhtml is translated.
2024-05-02 19:55:39,703 INFO  [net.sha.epu.cor.ser.EPubTranslatorServiceImpl] (main) OEBPS/Text/C_Sharp_Succinctly.html is translated.
2024-05-02 19:55:39,712 INFO  [net.sha.epu.cor.ser.EPubTranslatorServiceImpl] (main) OEBPS/Text/copyright.html is translated.
2024-05-02 19:55:39,713 INFO  [net.sha.epu.cor.ser.EPubTranslatorServiceImpl] (main) OEBPS/Text/cover_EPUB.html is translated.
2024-05-02 19:55:39,717 INFO  [net.sha.epu.cor.ser.EPubTranslatorServiceImpl] (main) OEBPS/Text/toc.html is translated.
java.io.IOException: Zugriff verweigert
        at java.base/java.io.FileOutputStream.write(Native Method)
        at java.base/java.io.FileOutputStream.write(FileOutputStream.java:313)
        at java.base/java.util.zip.ZipOutputStream.writeInt(ZipOutputStream.java:801)
        at java.base/java.util.zip.ZipOutputStream.writeLOC(ZipOutputStream.java:402)
        at java.base/java.util.zip.ZipOutputStream.putNextEntry(ZipOutputStream.java:247)
        at net.sharplab.epubtranslator.core.driver.epub.EPubWriter.write(EPubWriter.kt:15)
        at net.sharplab.epubtranslator.app.service.EPubTranslatorAppServiceImpl.translateEPubFile(EPubTranslatorAppServiceImpl.kt:13)
        at net.sharplab.epubtranslator.app.cli.EPubTranslatorCli.run(EPubTranslatorCli.kt:29)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at io.quarkus.picocli.runtime.PicocliRunner$EventExecutionStrategy.execute(PicocliRunner.java:26)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at io.quarkus.picocli.runtime.PicocliRunner.run(PicocliRunner.java:40)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:132)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
        Suppressed: java.io.IOException: Zugriff verweigert
                at java.base/java.io.FileOutputStream.writeBytes(Native Method)
                at java.base/java.io.FileOutputStream.write(FileOutputStream.java:349)
                at java.base/java.util.zip.DeflaterOutputStream.deflate(DeflaterOutputStream.java:261)
                at java.base/java.util.zip.ZipOutputStream.closeEntry(ZipOutputStream.java:265)
                at java.base/java.util.zip.ZipOutputStream.finish(ZipOutputStream.java:371)
                at java.base/java.util.zip.DeflaterOutputStream.close(DeflaterOutputStream.java:244)
                at java.base/java.util.zip.ZipOutputStream.close(ZipOutputStream.java:388)
                at kotlin.io.CloseableKt.closeFinally(Closeable.kt:59)
                at net.sharplab.epubtranslator.core.driver.epub.EPubWriter.write(EPubWriter.kt:12)
                ... 16 more
2024-05-02 19:55:39,743 INFO  [io.quarkus] (main) epub-translator stopped in 0.022s
```

I run the tool under windows in an admin terminal

I use 

java 17.0.11 2024-04-16 LTS
Java(TM) SE Runtime Environment Oracle GraalVM 17.0.11+7.1 (build 17.0.11+7-LTS-jvmci-23.0-b34)
Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 17.0.11+7.1 (build 17.0.11+7-LTS-jvmci-23.0-b34, mixed mode, sharing)

and the latest quarkus

I get the same error without a destination filename:

```
java -jar .\build\epub-translator-runner.jar --src "C# Succinctly - Joe Mayo.epub"
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2024-05-02 19:58:44,232 INFO  [io.quarkus] (main) epub-translator 0.7.0-SNAPSHOT on JVM (powered by Quarkus 3.10.0) started in 1.312s.
2024-05-02 19:58:44,233 INFO  [io.quarkus] (main) Profile prod activated.
2024-05-02 19:58:44,233 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, config-yaml, hibernate-orm, hibernate-orm-panache-kotlin, jdbc-h2, kotlin, narayana-jta, picocli, rest-client, rest-client-jackson, smallrye-context-propagation, vertx]
2024-05-02 19:58:44,781 INFO  [net.sha.epu.cor.ser.EPubTranslatorServiceImpl] (main) OEBPS/nav.xhtml is translated.
2024-05-02 19:58:46,308 INFO  [net.sha.epu.cor.ser.EPubTranslatorServiceImpl] (main) OEBPS/Text/C_Sharp_Succinctly.html is translated.
2024-05-02 19:58:46,318 INFO  [net.sha.epu.cor.ser.EPubTranslatorServiceImpl] (main) OEBPS/Text/copyright.html is translated.
2024-05-02 19:58:46,319 INFO  [net.sha.epu.cor.ser.EPubTranslatorServiceImpl] (main) OEBPS/Text/cover_EPUB.html is translated.
2024-05-02 19:58:46,323 INFO  [net.sha.epu.cor.ser.EPubTranslatorServiceImpl] (main) OEBPS/Text/toc.html is translated.
java.io.FileNotFoundException: C# Succinctly - Joe Mayo.de.epub (Das System kann die angegebene Datei nicht finden)
        at java.base/java.io.FileOutputStream.open0(Native Method)
        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:184)
        at net.sharplab.epubtranslator.core.driver.epub.EPubWriter.write(EPubWriter.kt:11)
        at net.sharplab.epubtranslator.app.service.EPubTranslatorAppServiceImpl.translateEPubFile(EPubTranslatorAppServiceImpl.kt:13)
        at net.sharplab.epubtranslator.app.cli.EPubTranslatorCli.run(EPubTranslatorCli.kt:29)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at io.quarkus.picocli.runtime.PicocliRunner$EventExecutionStrategy.execute(PicocliRunner.java:26)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at io.quarkus.picocli.runtime.PicocliRunner.run(PicocliRunner.java:40)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:132)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
2024-05-02 19:58:46,353 INFO  [io.quarkus] (main) epub-translator stopped in 0.026s
```

**Comment by Frogy76** [comment]
The Problem was the OneDrive Folder
