### ISSUE TITLE
Error during runtime

### ISSUE THREAD

**Issue by yborges** [sharplab/epub-translator#78]
```
java -jar epub-translator-runner.jar --src book_EN1.epub                                               
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2022-02-28 03:52:04,606 INFO  [io.quarkus] (main) epub-translator 0.6.2-SNAPSHOT on JVM (powered by Quarkus 2.7.2.Final) started in 1.407s. 
2022-02-28 03:52:04,613 INFO  [io.quarkus] (main) Profile prod activated. 
2022-02-28 03:52:04,614 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, config-yaml, hibernate-orm, hibernate-orm-panache-kotlin, jdbc-h2, kotlin, narayana-jta, picocli, rest-client, rest-client-jackson, smallrye-context-propagation]
net.sharplab.epubtranslator.core.driver.translator.DeepLTranslatorException: 403 error is thrown: <html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>

	at net.sharplab.epubtranslator.core.driver.translator.DeepLTranslator.translate(DeepLTranslator.kt:33)
	at net.sharplab.epubtranslator.core.service.EPubTranslatorServiceImpl.translateWithDeepL$lambda-4(EPubTranslatorServiceImpl.kt:183)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at net.sharplab.epubtranslator.core.service.EPubTranslatorServiceImpl.translateWithDeepL(EPubTranslatorServiceImpl.kt:180)
	at net.sharplab.epubtranslator.core.service.EPubTranslatorServiceImpl.translateEPubXhtmlDocument(EPubTranslatorServiceImpl.kt:56)
	at net.sharplab.epubtranslator.core.service.EPubTranslatorServiceImpl.translateEPubXhtmlString(EPubTranslatorServiceImpl.kt:42)
	at net.sharplab.epubtranslator.core.service.EPubTranslatorServiceImpl.translate(EPubTranslatorServiceImpl.kt:29)
	at net.sharplab.epubtranslator.app.service.EPubTranslatorAppServiceImpl.translateEPubFile(EPubTranslatorAppServiceImpl.kt:12)
	at net.sharplab.epubtranslator.app.cli.EPubTranslatorCli.run(EPubTranslatorCli.kt:29)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at io.quarkus.picocli.runtime.PicocliRunner$EventExecutionStrategy.execute(PicocliRunner.java:26)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at io.quarkus.picocli.runtime.PicocliRunner.run(PicocliRunner.java:40)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:124)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
Caused by: net.sharplab.deepl4j.client.ApiException: <html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>

	at net.sharplab.deepl4j.client.ApiClient.processResponse(ApiClient.java:842)
	at net.sharplab.deepl4j.client.ApiClient.invokeAPI(ApiClient.java:929)
	at net.sharplab.deepl4j.DeepLApi.translateTexts(DeepLApi.java:694)
	at net.sharplab.epubtranslator.core.driver.translator.DeepLTranslator.translate(DeepLTranslator.kt:29)
	... 22 more
2022-02-28 03:52:05,428 INFO  [io.quarkus] (main) epub-translator stopped in 0.014s
```

**Comment by ynojima** [comment]
Did you configure a valid DeepL api key?
https://github.com/sharplab/epub-translator#configuration

**Comment by yborges** [comment]
The config file is ./config/application.yml, in the subdirectory relative to where the application is being executed. I tested my api key using curl and I get a response. I also tried taking the epub file out the Downloads folder of my Mac and placing it in the same directory as the .jar. I'm still getting the same errors. I don't think configuration is the problem. By the way, the problem is showing up in both the built .jar I created from IntelliJ and from the last release I downloaded from GitHub. version 0.6.1.

**Comment by ynojima** [comment]
Oh, sorry, I found the cause.
Please replace `ePubTranslator.deepL.apiEndpoint` value "https://api.deepl.com/" with "https://api.deepl.com/v2/" in the `application.yml` file.
(If you are using free API plan, replace "https://api-free.deepl.com/" with "https://api-free.deepl.com/v2/".

**Comment by yborges** [comment]
That was a quick fix! Thanks for your help and this amazing project :)
