### ISSUE TITLE
403 error

### ISSUE THREAD

**Issue by yogcat** [sharplab/epub-translator#85]
Thanks for solving my issue!
I have build JDK 11 in my pc (didn't build GraalVM orDocker or Podman).

First, I downloaded Source code (zip) in your Release 0.6.1.RELEASE, and unpacked it in D:\translator\epub-translator-0.6.1.RELEASE.

Second, I created application.yml in D:\translator\epub-translator-0.6.1.RELEASE\config.
Here is what my application.yml write:
ePubTranslator:
  deepL:
    apiEndpoint: https://api-free.deepl.com/v2/ # If you subscribe free API plan, use "https://api-free.deepl.com/v2/" instead.
    apiKey: <my apikey>
  language:
    source: en        # default source language
    destination: zh-CN   # default destination language

Third, I used Git in D:\translator\epub-translator-0.6.1.RELEASE,using command:./gradlew quarkusBuild -Dquarkus.package.type=uber-jar,and all things built successfully.

Fourth, I tried to creat a uber.jar but I didn't know where to put those command you wrote or how, so I still use  Git in D:\translator\epub-translator-0.6.1.RELEASE,using command:java -jar build/epub-translator-runner.jar --src D:/Books/cooking/professionalcooking9th.epub --dst D:/Books/trans/professionalcooking9th.epub \
--srcLang en --dstLang zh-CN

And it turned out to be like this:
86189@DESKTOP-LA2D14O MINGW64 /d/translator/epub-translator-0.6.1.RELEASE
$ java -jar build/epub-translator-runner.jar --src D:/Books/cooking/professionalcooking9th.epub --dst D:/Books/trans/professionalcooking9th.epub \
--srcLang en --dstLang zh-CN
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2022-04-01 12:58:43,644 INFO  [io.quarkus] (main) epub-translator 0.6.1.RELEASE on JVM (powered by Quarkus 2.6.3.Final) started in 3.057s.
2022-04-01 12:58:43,661 INFO  [io.quarkus] (main) Profile prod activated.
2022-04-01 12:58:43,662 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, config-yaml, hibernate-orm, hibernate-orm-panache-kotlin, jdbc-h2, kotlin, narayana-jta, picocli, rest-client, rest-client-jackson, smallrye-context-propagation]
net.sharplab.epubtranslator.core.driver.translator.DeepLTranslatorException: 403 error is thrown:
        at net.sharplab.epubtranslator.core.driver.translator.DeepLTranslator.translate(DeepLTranslator.kt:33)
        at net.sharplab.epubtranslator.core.service.EPubTranslatorServiceImpl.translateWithDeepL$lambda-4(EPubTranslatorServiceImpl.kt:183)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at net.sharplab.epubtranslator.core.service.EPubTranslatorServiceImpl.translateWithDeepL(EPubTranslatorServiceImpl.kt:180)
        at net.sharplab.epubtranslator.core.service.EPubTranslatorServiceImpl.translateEPubXhtmlDocument(EPubTranslatorServiceImpl.kt:56)
        at net.sharplab.epubtranslator.core.service.EPubTranslatorServiceImpl.translateEPubXhtmlString(EPubTranslatorServiceImpl.kt:42)
        at net.sharplab.epubtranslator.core.service.EPubTranslatorServiceImpl.translate(EPubTranslatorServiceImpl.kt:29)
        at net.sharplab.epubtranslator.app.service.EPubTranslatorAppServiceImpl.translateEPubFile(EPubTranslatorAppServiceImpl.kt:12)
        at net.sharplab.epubtranslator.app.cli.EPubTranslatorCli.run(EPubTranslatorCli.kt:29)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at io.quarkus.picocli.runtime.PicocliRunner$EventExecutionStrategy.execute(PicocliRunner.java:26)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at io.quarkus.picocli.runtime.PicocliRunner.run(PicocliRunner.java:40)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:125)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
Caused by: net.sharplab.deepl4j.client.ApiException:
        at net.sharplab.deepl4j.client.ApiClient.processResponse(ApiClient.java:842)
        at net.sharplab.deepl4j.client.ApiClient.invokeAPI(ApiClient.java:929)
        at net.sharplab.deepl4j.DeepLApi.translateTexts(DeepLApi.java:694)
        at net.sharplab.epubtranslator.core.driver.translator.DeepLTranslator.translate(DeepLTranslator.kt:29)
        ... 22 more
2022-04-01 12:58:48,945 INFO  [io.quarkus] (main) epub-translator stopped in 0.027s

I'm wondering how I can successfully use deepl api,thanks again!

**Comment by ynojima** [comment]
Sorry for late response.
Have you filled `apiKey` in the application.yml?

**Comment by yogcat** [comment]
Yes, I did filll apiKey in the application.yml
First I filled apiKey with<>,like apiKey: <mykey>,it appeared 403 error, like I showed you before;
Then I deleted <> ,use apiKey: mykey, it appeared 400 error again,there is details Git showed me:
86189@DESKTOP-LA2D14O MINGW64 /d/translator/epub-translator-0.6.1.RELEASE
$ java -jar build/epub-translator-runner.jar --src D:/Books/cooking/professionalcooking9th.epub --dst D:/Books/trans/professionalcooking9th.epub \
--srcLang en --dstLang zh-CN
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2022-04-07 13:44:26,147 INFO  [io.quarkus] (main) epub-translator 0.6.1.RELEASE on JVM (powered by Quarkus 2.6.3.Final) started in 2.610s.
2022-04-07 13:44:26,161 INFO  [io.quarkus] (main) Profile prod activated.
2022-04-07 13:44:26,162 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, config-yaml, hibernate-orm, hibernate-orm-panache-kotlin, jdbc-h2, kotlin, narayana-jta, picocli, rest-client, rest-client-jackson, smallrye-context-propagation]
net.sharplab.epubtranslator.core.driver.translator.DeepLTranslatorException: **400 error** is thrown: {"message":"Value for 'target_lang' not supported."}
        at net.sharplab.epubtranslator.core.driver.translator.DeepLTranslator.translate(DeepLTranslator.kt:33)
        at net.sharplab.epubtranslator.core.service.EPubTranslatorServiceImpl.translateWithDeepL$lambda-4(EPubTranslatorServiceImpl.kt:183)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at net.sharplab.epubtranslator.core.service.EPubTranslatorServiceImpl.translateWithDeepL(EPubTranslatorServiceImpl.kt:180)
        at net.sharplab.epubtranslator.core.service.EPubTranslatorServiceImpl.translateEPubXhtmlDocument(EPubTranslatorServiceImpl.kt:56)
        at net.sharplab.epubtranslator.core.service.EPubTranslatorServiceImpl.translateEPubXhtmlString(EPubTranslatorServiceImpl.kt:42)
        at net.sharplab.epubtranslator.core.service.EPubTranslatorServiceImpl.translate(EPubTranslatorServiceImpl.kt:29)
        at net.sharplab.epubtranslator.app.service.EPubTranslatorAppServiceImpl.translateEPubFile(EPubTranslatorAppServiceImpl.kt:12)
        at net.sharplab.epubtranslator.app.cli.EPubTranslatorCli.run(EPubTranslatorCli.kt:29)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at io.quarkus.picocli.runtime.PicocliRunner$EventExecutionStrategy.execute(PicocliRunner.java:26)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at io.quarkus.picocli.runtime.PicocliRunner.run(PicocliRunner.java:40)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:125)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
Caused by: net.sharplab.deepl4j.client.ApiException: {"message":"Value for 'target_lang' not supported."}
        at net.sharplab.deepl4j.client.ApiClient.processResponse(ApiClient.java:842)
        at net.sharplab.deepl4j.client.ApiClient.invokeAPI(ApiClient.java:929)
        at net.sharplab.deepl4j.DeepLApi.translateTexts(DeepLApi.java:694)
        at net.sharplab.epubtranslator.core.driver.translator.DeepLTranslator.translate(DeepLTranslator.kt:29)
        ... 22 more
2022-04-07 13:44:31,438 INFO  [io.quarkus] (main) epub-translator stopped in 0.019s

**Comment by ynojima** [comment]
Thank you for update.
Please use `--dstLang ZH` instread of `--dstLang zh-CN` if you want to translate into Chinese.

**Comment by yogcat** [comment]
> Thank you for update. Please use `--dstLang ZH` instread of `--dstLang zh-CN` if you want to translate into Chinese.

Thank you so much! 
However, after several .xhtml been translated, it occurs mistake again:net.sharplab.epubtranslator.core.driver.translator.DeepLTranslatorException: 456 error is thrown: {"message":"Quota Exceeded"}
Thanks for answering!

**Comment by ynojima** [comment]
456 error is from DeepL API. It seems you have ran out of DeepL Free API character limit.
Please check this KB: https://support.deepl.com/hc/en-us/articles/360020681140-Error-code-456

**Comment by yogcat** [comment]
> 456 error is from DeepL API. It seems you have ran out of DeepL Free API character limit. Please check this KB: https://support.deepl.com/hc/en-us/articles/360020681140-Error-code-456

Ok, I just checked my account and it showed I really ran out of DeepL Free API character limit. I'll try next month.
Thank you again!
